name: CI - Lint & Type Check

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  lint-and-typecheck:
    name: Lint and Type Check
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run Format Check
        run: npm run format:check

      - name: Run Linter
        run: npm run lint

      - name: Run Type Check & Build
        run: npm run build

      - name: Check for build artifacts
        run: |
          if [ ! -d "dist" ]; then
            echo "Error: dist directory not created"
            exit 1
          fi
          echo "Build successful - dist directory exists"

  package-validation:
    name: Package Validation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm install

      - name: Run Build
        run: npm run build

      - name: Test Package (Dry Run)
        run: npm publish --dry-run

      - name: Validate package.json
        run: |
          node -e "
            const pkg = require('./package.json');

            // Check required fields
            const required = ['name', 'version', 'description', 'main', 'types', 'license'];
            const missing = required.filter(field => !pkg[field]);

            if (missing.length > 0) {
              console.error('Missing required fields:', missing.join(', '));
              process.exit(1);
            }

            // Check files array
            if (!pkg.files || pkg.files.length === 0) {
              console.error('files array is empty or missing');
              process.exit(1);
            }

            console.log('✓ package.json validation passed');
          "
